vim.keymap.set('n', '<F5>', function() require('dap').continue() end, { desc = 'DAP - Start Debugging' })
vim.keymap.set('n', '<F10>', function() require('dap').step_over() end, { desc = 'DAP - Step Over' })
vim.keymap.set('n', '<F11>', function() require('dap').step_into() end, { desc = 'DAP - Step Into' })
vim.keymap.set('n', '<F12>', function() require('dap').step_out() end, { desc = 'DAP - Step Out' })
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end, { desc = 'DAP - Toggle Breakpoint' })
vim.keymap.set('n', '<Leader>B', function() require('dap').set_breakpoint() end, { desc = 'DAP - Set Conditional Breakpoint' })
vim.keymap.set('n', '<Leader>lp', function() require('dap').set_breakpoint(nil, nil, vim.fn.input('Log point message: ')) end, { desc = 'DAP - Set Log Point' })
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end, { desc = 'DAP - Open REPL' })
vim.keymap.set('n', '<Leader>dl', function() require('dap').run_last() end, { desc = 'DAP - Run Last' })
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
  require('dap.ui.widgets').hover()
end, { desc = 'DAP UI - Hover Variables' })
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
  require('dap.ui.widgets').preview()
end, { desc = 'DAP UI - Preview Variables' })
vim.keymap.set('n', '<Leader>df', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.frames)
end, { desc = 'DAP UI - Show Frames' })
vim.keymap.set('n', '<Leader>ds', function()
  local widgets = require('dap.ui.widgets')
  widgets.centered_float(widgets.scopes)
end, { desc = 'DAP UI - Show Scopes' })
